site_name: Life of a KU Faculty
theme:
  name: material
  features:
    - navigation.instant
  icon:
    admonition:
      quote: fontawesome/solid/quote-left

markdown_extensions:
  - admonition
  - pymdownx.details